### PR TITLE
theme modernize, deps optimizing

### PR DESCRIPTION
**Pull request by SaltyMonkey**
more like modern look, slight moved tabs, clear log button, changed theme color in settings

### CODE REVIEW

**Comment by SaltyMonkey** [comment]
https://github.com/tera-toolbox/tera-toolbox/pull/27/commits/7a70d3fcb35ece933a7dd4f7dee9fdb1e51ec014
switching npm dep from process-list to ps-list.
Reason: process-list using managed/unmanaged code which is slow, it also using wmi interface which is slow and cpu heavy. Ps-list using simple af binary which using win32api and wrapper with stdout, it a lot faster and using almost 0 cpu. 

Example (i5-6600): 
```
electron+process-list: 7-10% cpu usage
electron+ps-list: 0-2% cpu usage
```

**Comment by SaltyMonkey** [comment]
tho it looks like it trying to read file every call...
not sure if it healtly for hdd/ssd
need to edit https://github.com/MarkTiedemann/fastlist/blob/master/fastlist.cpp
to do start-> check process until stop/start in `cin`

**Comment by SaltyMonkey** [comment]
rolled back client interface changes back (it kinda can kill SSD/HDDs)

**Comment by caali-hackerman** [comment]
Most of the proposed changes have been integrated. Thanks!

**Pull request closed without merging**
